Web/Models/Thread.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Web.Models
{
    public class Thread
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public DateTime DateTime { get; set; }
        public Thread()
        {
            DateTime = DateTime.Now;
        }


        public int BoardId { get; set; }
        public Board Board { get; set; }


        public ICollection<Post> Posts { get; set; }
    }
}

Web/Controllers/ThreadController.cs
using Web.Models;
using Microsoft.AspNetCore.Mvc;
using Web.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Web.Controllers
{
    public class ThreadController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly IThreadRepository _threadRepository;

        public ThreadController(IPostRepository postRepository,
                                IThreadRepository threadRepository)
        {
            _postRepository = postRepository;
            _threadRepository = threadRepository;
        }

        public IActionResult Index(int threadId)
        {

            ThreadIndexViewModel model = new ThreadIndexViewModel();
            model.Thread = _threadRepository.GetById(threadId);
            model.ThreadId = model.Thread.Id;
            model.Username = User.Identity.Name;
            return View(model);
        }

        [Authorize(Roles= "Admin, User")]
        [HttpPost]
        public IActionResult WritePost(ThreadIndexViewModel model)
        {
            

            if (model.CreatePostViewModel.Content != null)
            {
                Post newPost = new Post
                {
                    Content = model.CreatePostViewModel.Content,
                    ThreadId = model.ThreadId,
                    User = User.Identity.Name
            };
                _postRepository.Add(newPost);

                return RedirectToAction("index", new { threadId = model.ThreadId });
            }

            model.Thread = _threadRepository.GetById(model.ThreadId);
            model.Username = User.Identity.Name;

            return View("Index", model);
        }

        [Authorize(Roles = "Admin, User")]
        [HttpPost]
        public IActionResult WriteReply(ThreadIndexViewModel model)
        {
            if (model.CreateReplyViewModel.Content != null)
            {
                if (model.SubmitType == "Reply")
                {
                    Post newPost = new Post
                    {
                        Content = model.CreateReplyViewModel.Content,
                        ThreadId = model.ThreadId,
                        ReplyId = model.ReplyId,
                        User = User.Identity.Name
                    };
                    _postRepository.Add(newPost);
                }
                else if (model.SubmitType == "Update")
                {
                    Post updatePost = _postRepository.GetById(model.UpdateId);
                    updatePost.Id = model.UpdateId;
                    updatePost.Content = model.CreateReplyViewModel.Content;
                    _postRepository.Update(updatePost);
                }
                else if(model.SubmitType == "Delete")
                {
                    _postRepository.Delete(model.DeleteId);
                }

                return RedirectToAction("index", new { threadId = model.ThreadId });
            }

            model.Thread = _threadRepository.GetById(model.ThreadId);
            model.Username = User.Identity.Name;

            return View("Index", model);
        }

        [Authorize(Roles= "Admin, User")]
        [HttpPost]
        public IActionResult DeletePost(ThreadIndexViewModel model)
        {
            _postRepository.Delete(model.DeleteId);
            return RedirectToAction("index", new { threadId = model.ThreadId });
        }
    }
}

Web/Views/Thread/Index.cshtml
@model ThreadIndexViewModel


@section Styles{
    <style>
        blockquote {
            background: #f9f9f9;
            border-left: 10px solid #ccc;
            margin: 1.5em 10px;
            padding: 0.5em 10px;
            quotes: "\201C""\201D""\2018""\2019";
            word-break: break-all;
        }

            blockquote p:before {
                color: #ccc;
                font-size: 4em;
                line-height: 0.1em;
                margin-right: 0.25em;
                vertical-align: -0.4em;
            }

            blockquote p {
                display: inline;
            }

        .delete {
            background: none !important;
            border: none;
            padding: 0 !important;
        }
    </style>
}
<h3>Thread: @Model.Thread.Title</h3>


<div asp-validation-summary="All" class="text-danger"></div>

<div class="d-flex" style="overflow: hidden; border: solid 2px black;">
    <div style="width: 20%; background: #343a40; color: white; word-break: break-word;">
        <div style="margin: 5pt;">
            <div style="border-bottom: 1pt solid white">
                @Model.Thread.Posts.FirstOrDefault().User
            </div>
            <div s>
                @Model.Thread.Posts.FirstOrDefault().DateTime
            </div>
        </div>

    </div>
    <div style="width: 80%; background: #cbe3f5;">
        <div style="margin: 5pt;">
            @Model.Thread.Posts.FirstOrDefault().Content
        </div>
    </div>
</div>
<form asp-controller="Thread" asp-action="WritePost" method="post">
    @Html.HiddenFor(model => model.ThreadId)
    <textarea asp-for="CreatePostViewModel.Content" class="form-control mt-2" rows="4" style="resize: none;"></textarea>
    <div class="d-flex justify-content-end">
        <button type="submit" style="text-decoration: underline; border:none; background: none">Write Post</button>
    </div>
</form>

<div class="mb-5"></div>
@foreach (var post in Model.Thread.Posts.Skip(1))
{
    <div class="mb-4">
        <div style="border: solid 2px black;">
            <div class="d-flex" style="overflow: hidden;">
                <div class="d-flex flex-column" style="width: 20%; background: #343a40; color: white; padding: 5pt;">
                    <div class="mb-auto" style="border-bottom: 1pt solid white;">
                        @post.User
                    </div>
                    <div>
                        @post.DateTime
                    </div>
                </div>
                <div style="width: 80%; background: #cbe3f5;">
                    @if (post.Reply != null)
                    {
                        <blockquote><div class="mb-3">@post.Reply.User</div><div class="d-flex"><i class="fas fa-quote-left" style="font-size: 10pt"></i><p class="mt-1"> &nbsp &nbsp @post.Reply.Content</p></div></blockquote>

                    }
                    <div style="margin: 5pt; word-break:break-all;">
                        @post.Content
                    </div>
                </div>
            </div>
            @if (post.Content != "[This post has been removed]" && (post.User == Model.Username || User.IsInRole("Admin")))
            {
                <form asp-controller="Thread" asp-action="DeletePost" method="post">
                    @Html.HiddenFor(model => model.ThreadId)
                    <div id=@(post.Id.ToString() + "ReplyEditBar") style="background: rgba(255, 255, 255, 0.7); border-top: solid 1px black;">
                        <div class="d-flex justify-content-end">
                            <button class="m-2 delete" style="font-size: 12px" type="submit" onclick="return deletePost(this, @post.Id);"><i class="fas fa-trash"></i> Delete</button>
                            @if (post.User == Model.Username)
                            {
                                <span class="m-2" style="font-size: 12px; cursor: pointer;" onclick="replyOrEdit((@post.Id).toString(), this.innerText);"><i class="fas fa-edit"></i> Edit</span>

                            }
                        </div>
                    </div>
                </form>
            }
            else if (post.Content != "[This post has been removed]" && Model.Username != null)
            {
                <div id=@(post.Id.ToString() + "ReplyEditBar") style="background: rgba(255, 255, 255, 0.7); border-top: solid 1px black;">
                    <div class="d-flex justify-content-end">
                        <span class="m-2" style="font-size: 12px; cursor: pointer;" onclick="replyOrEdit((@post.Id).toString(), this.innerText)"><i class="fas fa-reply"></i> Reply</span>
                    </div>
                </div>
            }
        </div>
        <div id=@(post.Id.ToString() + "Form") style="display: none;">
            <form asp-controller="Thread" asp-action="WriteReply" method="post">
                @Html.HiddenFor(model => model.ThreadId)
                @Html.Hidden("ReplyId", post.Id)
                <textarea asp-for="CreateReplyViewModel.Content" id=@(post.Id.ToString() + "Textarea") class="form-control mt-1" rows="4" style="resize: none;"></textarea>
                <div class="d-flex justify-content-end mb-5" style="font-size: 12px; background: rgba(255, 255, 255, 0.7);">
                    <i class="fas fa-times p-2 mr-auto" style="cursor: pointer;" onclick="endReplyOrEdit( (@post.Id).toString())"></i>
                    <button id="@(post.Id.ToString() + "SubmitReply")" onclick="submitReply(this, @post.Id);" type="submit" style="text-decoration: underline; border:none; background: none;">Write Reply</button>
                    <button id="@(post.Id.ToString() + "SubmitEdit")" onclick="submitReply(this, @post.Id);" type="submit" style="text-decoration: underline; border:none; background: none;">Update Reply</button>
                </div>
            </form>
        </div>
    </div>
}

@section Scripts{
    <script type="text/javascript">
        function replyOrEdit(id, innerText) {
            document.getElementById(id + "ReplyEditBar").style.display = 'none';
            document.getElementById(id + "Form").style.display = null;
            if (innerText.includes("Edit")) {
                document.getElementById(id + "SubmitReply").style.display = 'none';
                document.getElementById(id + "SubmitEdit").style.display = null;
            } else if (innerText.includes("Reply")) {
                document.getElementById(id + "SubmitReply").style.display = null;
                document.getElementById(id + "SubmitEdit").style.display = 'none';
            }
        }

        function endReplyOrEdit(id) {
            document.getElementById(id + "ReplyEditBar").style.display = null;
            document.getElementById(id + "Form").style.display = 'none';
        }

        function submitReply(element, id) {
            var hiddenInput = document.createElement("input");
            hiddenInput.id = "SubmitType";
            hiddenInput.name = "SubmitType";
            hiddenInput.type = "hidden";
            if (element.innerText == "Write Reply") {
                hiddenInput.value = "Reply"
            }
            else if (element.innerText == "Update Reply") {
                hiddenInput.value = "Update"
                var hiddenInputForId = document.createElement("input");
                hiddenInputForId.id = "UpdateId";
                hiddenInputForId.name = "UpdateId";
                hiddenInputForId.type = "hidden";
                hiddenInputForId.value = id;
                element.appendChild(hiddenInputForId);
            }
            element.appendChild(hiddenInput);
            return true;
        }

        function deletePost(element, id) {

            if (confirm("Are you sure you want to delete your post?")) {
                var hiddenInputForId = document.createElement("input");
                hiddenInputForId.id = "DeleteId";
                hiddenInputForId.name = "DeleteId";
                hiddenInputForId.type = "hidden";
                hiddenInputForId.value = id;
                element.appendChild(hiddenInputForId);
                return true;
            } else {
                return false;
            }
        }
    </script>
}