Web/Models/Board.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Web.Models
{
    public class Board
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }


        public ICollection<Thread> Threads { get; set;}
    }
}

Web/ViewModels/CreateThreadViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Web.ViewModels
{
    public class CreateThreadViewModel
    {
        [Required]
        public string Title { get; set; }
        public int BoardId { get; set; }
        public string BoardTitle { get; set; }
        public DateTime DateTime { get; set; }
        [Required]
        public string Content { get; set; }
        public CreateThreadViewModel()
        {
            DateTime = DateTime.Now;
        }
    }
}

Web/Controllers/BoardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Web.Models;
using Web.ViewModels;

namespace Web.Controllers
{
    public class BoardController : Controller
    {

        private readonly IBoardRepository _boardRepository;
        private readonly IPostRepository _postRepository;
        private readonly IThreadRepository _threadRepository;

        public BoardController(IBoardRepository boardRepository,
                              IPostRepository postRepository,
                              IThreadRepository threadRepository)
        {
            _boardRepository = boardRepository;
            _postRepository = postRepository;
            _threadRepository = threadRepository;
        }

        public IActionResult Index(int boardId)
        {
            BoardIndexViewModel model = new BoardIndexViewModel();
            model.Board = _boardRepository.GetById(boardId);
            model.ThreadViewModels = new List<BoardIndexThreadViewModel>();


            foreach (var thread in model.Board.Threads)
            {
                BoardIndexThreadViewModel boardIndexThreadViewModel = new BoardIndexThreadViewModel();
                boardIndexThreadViewModel.Thread = thread;
                boardIndexThreadViewModel.RepliesCount = thread.Posts.Count();
                boardIndexThreadViewModel.lastPost = thread.Posts.OrderBy(p => p.DateTime).LastOrDefault();
                model.ThreadViewModels.Add(boardIndexThreadViewModel);
            }

            return View(model);
        }

        [Authorize(Roles= "Admin, User")]
        [HttpGet]
        public ViewResult CreateThread(int boardId)
        {
            CreateThreadViewModel model = new CreateThreadViewModel();
            model.BoardTitle = _boardRepository.GetById(boardId).Title;
            model.BoardId = boardId;
            return View(model);
        }

        [Authorize(Roles = "Admin, User")]
        [HttpPost]
        public IActionResult CreateThread(CreateThreadViewModel model)
        {
            if (ModelState.IsValid)
            {
                Thread newThread = new Thread
                {
                    Title = model.Title,
                    BoardId = model.BoardId
                };
                _threadRepository.Add(newThread);

                Post newPost = new Post
                {
                    Content = model.Content,
                    ThreadId = newThread.Id,
                    User = User.Identity.Name
                };
                _postRepository.Add(newPost);

                return RedirectToAction("index", new { boardId = model.BoardId });
            }
            return View(model);
        }
    }
}

Web/Views/Board/CreateThread.cshtml
@model CreateThreadViewModel

@{
    ViewBag.Title = $"Create {Model.BoardTitle} Thread";
}

    <form asp-controller="Board" asp-action="CreateThread" method="post">
        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input type="text" class="form-control" asp-for="Title">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Content">Thread Content</label>
            <textarea asp-for="Content" class="form-control" rows="5" style="resize: none;"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
        @Html.HiddenFor(model => model.BoardId)
        @Html.HiddenFor(model => model.BoardTitle)
        <div class="form-group d-flex just">
            <button type="submit" class="btn btn-success">Create</button>
        </div>
    </form>

Web/Views/Board/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@model BoardIndexViewModel

@{
    ViewBag.Title = Model.Board.Title + " Board";
}

@section Styles{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
}

<div class="d-flex justify-content-end">
    <a asp-controller="board" asp-action="CreateThread" asp-route-boardId=@Model.Board.Id class="btn btn-light mb-2">Post Thread</a>
</div>
<table id="table_id" class="table">
    <thead class="thead-light">
        <tr>
            <th width="50%">Thread</th>
            <th width="20%">Replies</th>
            <th width="25%">Last Post</th>
            <th nowrap></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var thread in Model.ThreadViewModels)
        {
            <tr style="background-color:rgba(128, 128, 128, 0.8) !important;">
                <th>
                    <a asp-controller="thread" asp-action="index" asp-route-threadId=@thread.Thread.Id style="color: white;">@thread.Thread.Title</a>
                </th>
                <td>@(thread.RepliesCount - 1)</td>
                <td>
                    <div>
                        @thread.lastPost.User
                    </div>
                    <div>
                        @thread.lastPost.DateTime
                    </div>
                </td>
                <td>
                    @if (SignInManager.IsSignedIn(User) && (User.IsInRole("Admin")))
                    {
                        <a class="btn btn-sm btn-danger" onclick="deleteBoard('@thread.Thread.Title', '@thread.Thread.Id')"><i class="fas fa-trash"></i></a>
                    }

                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#table_id').DataTable({
                "ordering": false,
                "searching": false
            });
        });

        function deleteBoard(thread, threadId) {
            if (confirm("Are you sure you want to delete thread: " + thread + "?")) {
                window.location.href = '@Url.Action("DeleteThread", "Admin")/?threadId=' + threadId;
            }

        }
    </script>
}